require("kanagawa").setup({
	undercurl = true,
	commentStyle = { italic = true },
	functionStyle = {},
	keywordStyle = { italic = true },
	statementStyle = { bold = true },
	typeStyle = {},
	variablebuiltinStyle = { italic = true },
	specialReturn = true,
	specialException = true,
	transparent = false,
	dimInactive = false,
	globalStatus = false,
	colors = {},
	overrides = {},
})
