local set = vim.opt
local global = vim.g

global.mapleader = " "
global.filetype = "plugin indent on"

set.termguicolors = true
set.pumheight = 18
set.encoding = "utf-8"
set.fileencoding = "utf-8"
set.cmdheight = 0
set.splitright = true
set.tabstop = 2
set.shiftwidth = 2
set.expandtab = true
set.smartindent = true
set.laststatus = 3
set.ignorecase = true
set.background = "dark"
set.showtabline = 0
set.updatetime = 100
set.timeoutlen = 500
set.clipboard = "unnamedplus"
set.scrolloff = 8
set.fileformats = { "unix", "dos" }
set.swapfile = false
set.modeline = false
set.hlsearch = false
set.signcolumn = "yes"
set.cursorline = true
set.number = true
set.relativenumber = true
set.exrc = true
